# Generated by Django 3.2.3 on 2021-06-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='amir', max_length=150)),
                ('author', models.CharField(default='amir', max_length=150)),
                ('tranlator', models.CharField(default='amir', max_length=150)),
                ('year', models.CharField(default='amir', max_length=150)),
                ('format_book', models.CharField(default='amir', max_length=150)),
                ('number_of_pages', models.CharField(default='amir', max_length=150)),
                ('language', models.CharField(default='amir', max_length=150)),
                ('ISBN', models.CharField(default='amir', max_length=150)),
                ('contents', models.TextField()),
                ('publisher', models.CharField(default='amir', max_length=150)),
                ('description', models.TextField()),
                ('average', models.IntegerField(blank=True, default=0, null=True)),
                ('counter', models.IntegerField(blank=True, default=0, null=True)),
                ('num_sold', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.IntegerField(default=10000)),
                ('image', models.ImageField(upload_to='')),
                ('grouping', models.CharField(choices=[('ادبیات', (('1', 'ادبیات پارسی'), ('2', 'ادبیات جهان'), ('3', 'نگارش'), ('4', 'شعر پارسی'), ('5', 'شعر خارجی'), ('6', 'طنز'), ('7', 'فرهنگ لغت'), ('8', 'زندگی نامه و خاطرات'), ('9', 'سفرنامه'), ('13', 'نقد و برسی'))), ('داستان و رمان', (('10', 'رمان های خارجی'), ('16', 'رمان های ایرانی'))), ('روان شناسی', (('17', 'موفقیت'), ('18', 'خانواده و روابط'), ('19', 'خودسازی'), ('20', 'ارتباطات'), ('21', 'بزرگسال'), ('22', 'کودک و نوجوان'))), ('اقتصاد و مدیریت', (('23', 'بازاریابی و فروش'), ('24', 'مدیریت و رهبری'), ('25', 'کارآفرینی'), ('26', 'حسابداری'), ('27', 'سرمایه گذاری و بورس'), ('28', 'مدیریت پروژه'), ('29', 'امور مالی و بیمه'), ('30', 'مدیریت سازمان'), ('31', 'اقتصاد'), ('32', 'گزارش\u200cهای آماری'))), ('کامپیوتر', (('33', 'آموزش کامپیوتر و اینترنت'), ('34', 'سیستم عامل'), ('35', 'برنامه نویسی'), ('36', 'تجارت الکترونیک'), ('37', 'هک و امنیت'), ('38', 'آموزش شبکه'), ('39', 'سخت افزار'), ('40', 'طراحی وب سایت'), ('41', 'گرافیک کامپیوتری و انیمیشن')))], default='برنامه نویسی', max_length=5555550)),
            ],
        ),
        migrations.CreateModel(
            name='opinions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(default=0)),
                ('book_name', models.CharField(max_length=150)),
                ('user', models.CharField(default='amir13roshan80@gmail.com', max_length=150)),
                ('opinion', models.TextField(max_length=50000)),
                ('star', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(default=0)),
                ('book_name', models.CharField(max_length=150)),
                ('user', models.CharField(default='amir', max_length=150)),
            ],
        ),
    ]
