# Generated by Django 3.2.3 on 2021-06-03 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_rest_', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='data_buy',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 16, 13, 58, 281335)),
        ),
        migrations.AddField(
            model_name='sold',
            name='price',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
