# Generated by Django 3.2.3 on 2021-06-03 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_rest_', '0002_auto_20210603_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_table',
            name='file_detail',
            field=models.FileField(default='1.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='book_table',
            name='file_full',
            field=models.FileField(default='1.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='sold',
            name='data_buy',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 16, 29, 24, 436693)),
        ),
    ]
