# Generated by Django 3.2.3 on 2021-06-04 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_rest_', '0003_auto_20210603_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinions',
            name='star',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sold',
            name='data_buy',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 4, 16, 19, 1, 62946)),
        ),
    ]
