# Generated by Django 3.2.3 on 2021-06-04 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_rest_', '0004_auto_20210604_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinions',
            name='star',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sold',
            name='data_buy',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 4, 16, 20, 20, 216518)),
        ),
    ]
