# Generated by Django 3.2.3 on 2021-06-04 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_rest_', '0005_auto_20210604_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_table',
            name='average',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sold',
            name='data_buy',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 4, 16, 20, 46, 291677)),
        ),
    ]
