# Generated by Django 3.2.3 on 2021-06-07 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_rest_', '0011_auto_20210606_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='mark_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(default=0)),
                ('book_name', models.CharField(max_length=150)),
                ('user', models.CharField(default='amir', max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='book_table',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 11, 41, 38, 440119)),
        ),
        migrations.AlterField(
            model_name='sold',
            name='data_buy',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 11, 41, 38, 439119)),
        ),
    ]
