# Generated by Django 3.2.3 on 2021-06-09 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_rest_', '0013_auto_20210609_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_list',
            name='price',
        ),
        migrations.AlterField(
            model_name='book_table',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 9, 10, 38, 31, 84742)),
        ),
        migrations.AlterField(
            model_name='sold',
            name='data_buy',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 9, 10, 38, 31, 82743)),
        ),
    ]
