# Generated by Django 3.2.3 on 2021-06-16 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_rest_', '0027_auto_20210614_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_table',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 15, 43, 7, 229625)),
        ),
        migrations.AlterField(
            model_name='sold',
            name='data_buy',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 15, 43, 7, 227626)),
        ),
    ]
