# Generated by Django 3.2.4 on 2021-07-07 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_rest_', '0031_auto_20210628_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_table',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 4, 56, 37, 328583)),
        ),
        migrations.AlterField(
            model_name='sold',
            name='data_buy',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 4, 56, 37, 327227)),
        ),
    ]
