# Generated by Django 3.2.3 on 2021-06-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20210601_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='data_join',
            field=models.DateField(auto_now_add=True, verbose_name='data join'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateField(auto_now=True, verbose_name='last login'),
        ),
    ]
