# Generated by Django 3.2.3 on 2021-06-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20210601_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='data_join',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data join'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='last login'),
        ),
    ]
